COUNTRIES_DICT = {
    'Aruba': ('ABW', 'AW'),
    'Afghanistan': ('AFG', 'AF'),
    'Angola': ('AGO', 'AO'),
    'Anguilla': ('AIA', 'AI'),
    'Åland Islands': ('ALA', 'AX'),
    'Albania': ('ALB', 'AL'),
    'Andorra': ('AND', 'AD'),
    'United Arab Emirates': ('ARE', 'AE'),
    'Argentina': ('ARG', 'AR'),
    'Armenia': ('ARM', 'AM'),
    'American Samoa': ('ASM', 'AS'),
    'Antarctica': ('ATA', 'AQ'),
    'French Southern Territories': ('ATF', 'TF'),
    'Antigua and Barbuda': ('ATG', 'AG'),
    'Australia': ('AUS', 'AU'),
    'Austria': ('AUT', 'AT'),
    'Azerbaijan': ('AZE', 'AZ'),
    'Burundi': ('BDI', 'BI'),
    'Belgium': ('BEL', 'BE'),
    'Benin': ('BEN', 'BJ'),
    'Bonaire, Sint Eustatius and Saba': ('BES', 'BQ'),
    'Burkina Faso': ('BFA', 'BF'),
    'Bangladesh': ('BGD', 'BD'),
    'Bulgaria': ('BGR', 'BG'),
    'Bahrain': ('BHR', 'BH'),
    'Bahamas': ('BHS', 'BS'),
    'Bosnia and Herzegovina': ('BIH', 'BA'),
    'Saint Barthélemy': ('BLM', 'BL'),
    'Belarus': ('BLR', 'BY'),
    'Belize': ('BLZ', 'BZ'),
    'Bermuda': ('BMU', 'BM'),
    'Bolivia (Plurinational State of)': ('BOL', 'BO'),
    'Brazil': ('BRA', 'BR'),
    'Barbados': ('BRB', 'BB'),
    'Brunei Darussalam': ('BRN', 'BN'),
    'Bhutan': ('BTN', 'BT'),
    'Bouvet Island': ('BVT', 'BV'),
    'Botswana': ('BWA', 'BW'),
    'Central African Republic': ('CAF', 'CF'),
    'Canada': ('CAN', 'CA'),
    'Cocos (Keeling) Islands': ('CCK', 'CC'),
    'Switzerland': ('CHE', 'CH'),
    'Chile': ('CHL', 'CL'),
    'China': ('CHN', 'CN'),
    "Côte d'Ivoire": ('CIV', 'CI'),
    'Cameroon': ('CMR', 'CM'),
    'Congo, Democratic Republic of the': ('COD', 'CD'),
    'Congo': ('COG', 'CG'),
    'Cook Islands': ('COK', 'CK'),
    'Colombia': ('COL', 'CO'),
    'Comoros': ('COM', 'KM'),
    'Cabo Verde': ('CPV', 'CV'),
    'Costa Rica': ('CRI', 'CR'),
    'Cuba': ('CUB', 'CU'),
    'Curaçao': ('CUW', 'CW'),
    'Christmas Island': ('CXR', 'CX'),
    'Cayman Islands': ('CYM', 'KY'),
    'Cyprus': ('CYP', 'CY'),
    'Czechia (Czech Republic)': ('CZE', 'CZ'),
    'Germany': ('DEU', 'DE'),
    'Djibouti': ('DJI', 'DJ'),
    'Dominica': ('DMA', 'DM'),
    'Denmark': ('DNK', 'DK'),
    'Dominican Republic': ('DOM', 'DO'),
    'Algeria': ('DZA', 'DZ'),
    'Ecuador': ('ECU', 'EC'),
    'Egypt': ('EGY', 'EG'),
    'Eritrea': ('ERI', 'ER'),
    'Western Sahara': ('ESH', 'EH'),
    'Spain': ('ESP', 'ES'),
    'Estonia': ('EST', 'EE'),
    'Ethiopia': ('ETH', 'ET'),
    'Finland': ('FIN', 'FI'),
    'Fiji': ('FJI', 'FJ'),
    'Falkland Islands (Malvinas)': ('FLK', 'FK'),
    'France': ('FRA', 'FR'),
    'Faroe Islands': ('FRO', 'FO'),
    'Micronesia (Federated States of)': ('FSM', 'FM'),
    'Gabon': ('GAB', 'GA'),
    'United Kingdom of Great Britain and Northern Ireland': ('GBR', 'GB'),
    'Georgia': ('GEO', 'GE'),
    'Guernsey': ('GGY', 'GG'),
    'Ghana': ('GHA', 'GH'),
    'Gibraltar': ('GIB', 'GI'),
    'Guinea': ('GIN', 'GN'),
    'Guadeloupe': ('GLP', 'GP'),
    'Gambia': ('GMB', 'GM'),
    'Guinea-Bissau': ('GNB', 'GW'),
    'Equatorial Guinea': ('GNQ', 'GQ'),
    'Greece': ('GRC', 'GR'),
    'Grenada': ('GRD', 'GD'),
    'Greenland': ('GRL', 'GL'),
    'Guatemala': ('GTM', 'GT'),
    'French Guiana': ('GUF', 'GF'),
    'Guam': ('GUM', 'GU'),
    'Guyana': ('GUY', 'GY'),
    'Hong Kong': ('HKG', 'HK'),
    'Heard Island and McDonald Islands': ('HMD', 'HM'),
    'Honduras': ('HND', 'HN'),
    'Croatia': ('HRV', 'HR'),
    'Haiti': ('HTI', 'HT'),
    'Hungary': ('HUN', 'HU'),
    'Indonesia': ('IDN', 'ID'),
    'Isle of Man': ('IMN', 'IM'),
    'India': ('IND', 'IN'),
    'British Indian Ocean Territory': ('IOT', 'IO'),
    'Ireland': ('IRL', 'IE'),
    'Iran (Islamic Republic of)': ('IRN', 'IR'),
    'Iraq': ('IRQ', 'IQ'),
    'Iceland': ('ISL', 'IS'),
    'Israel': ('ISR', 'IL'),
    'Italy': ('ITA', 'IT'),
    'Jamaica': ('JAM', 'JM'),
    'Jersey': ('JEY', 'JE'),
    'Jordan': ('JOR', 'JO'),
    'Japan': ('JPN', 'JP'),
    'Kazakhstan': ('KAZ', 'KZ'),
    'Kenya': ('KEN', 'KE'),
    'Kyrgyzstan': ('KGZ', 'KG'),
    'Cambodia': ('KHM', 'KH'),
    'Kiribati': ('KIR', 'KI'),
    'Saint Kitts and Nevis': ('KNA', 'KN'),
    'Korea, Republic of': ('KOR', 'KR'),
    'Kuwait': ('KWT', 'KW'),
    "Lao People's Democratic Republic": ('LAO', 'LA'),
    'Lebanon': ('LBN', 'LB'),
    'Liberia': ('LBR', 'LR'),
    'Libya': ('LBY', 'LY'),
    'Saint Lucia': ('LCA', 'LC'),
    'Liechtenstein': ('LIE', 'LI'),
    'Sri Lanka': ('LKA', 'LK'),
    'Lesotho': ('LSO', 'LS'),
    'Lithuania': ('LTU', 'LT'),
    'Luxembourg': ('LUX', 'LU'),
    'Latvia': ('LVA', 'LV'),
    'Macao': ('MAC', 'MO'),
    'Saint Martin (French part)': ('MAF', 'MF'),
    'Morocco': ('MAR', 'MA'),
    'Monaco': ('MCO', 'MC'),
    'Moldova, Republic of': ('MDA', 'MD'),
    'Madagascar': ('MDG', 'MG'),
    'Maldives': ('MDV', 'MV'),
    'Mexico': ('MEX', 'MX'),
    'Marshall Islands': ('MHL', 'MH'),
    'North Macedonia': ('MKD', 'MK'),
    'Mali': ('MLI', 'ML'),
    'Malta': ('MLT', 'MT'),
    'Myanmar': ('MMR', 'MM'),
    'Montenegro': ('MNE', 'ME'),
    'Mongolia': ('MNG', 'MN'),
    'Northern Mariana Islands': ('MNP', 'MP'),
    'Mozambique': ('MOZ', 'MZ'),
    'Mauritania': ('MRT', 'MR'),
    'Montserrat': ('MSR', 'MS'),
    'Martinique': ('MTQ', 'MQ'),
    'Mauritius': ('MUS', 'MU'),
    'Malawi': ('MWI', 'MW'),
    'Malaysia': ('MYS', 'MY'),
    'Mayotte': ('MYT', 'YT'),
    'Namibia': ('NAM', 'NA'),
    'New Caledonia': ('NCL', 'NC'),
    'Niger': ('NER', 'NE'),
    'Norfolk Island': ('NFK', 'NF'),
    'Nigeria': ('NGA', 'NG'),
    'Nicaragua': ('NIC', 'NI'),
    'Niue': ('NIU', 'NU'),
    'Netherlands': ('NLD', 'NL'),
    'Norway': ('NOR', 'NO'),
    'Nepal': ('NPL', 'NP'),
    'Nauru': ('NRU', 'NR'),
    'New Zealand': ('NZL', 'NZ'),
    'Oman': ('OMN', 'OM'),
    'Pakistan': ('PAK', 'PK'),
    'Panama': ('PAN', 'PA'),
    'Pitcairn': ('PCN', 'PN'),
    'Peru': ('PER', 'PE'),
    'Philippines': ('PHL', 'PH'),
    'Palau': ('PLW', 'PW'),
    'Papua New Guinea': ('PNG', 'PG'),
    'Poland': ('POL', 'PL'),
    'Puerto Rico': ('PRI', 'PR'),
    "Korea (Democratic People's Republic of)": ('PRK', 'KP'),
    'Portugal': ('PRT', 'PT'),
    'Paraguay': ('PRY', 'PY'),
    'Palestine, State of': ('PSE', 'PS'),
    'French Polynesia': ('PYF', 'PF'),
    'Qatar': ('QAT', 'QA'),
    'Réunion': ('REU', 'RE'),
    'Romania': ('ROU', 'RO'),
    'Russian Federation': ('RUS', 'RU'),
    'Rwanda': ('RWA', 'RW'),
    'Saudi Arabia': ('SAU', 'SA'),
    'Sudan': ('SDN', 'SD'),
    'Senegal': ('SEN', 'SN'),
    'Singapore': ('SGP', 'SG'),
    'South Georgia and the South Sandwich Islands': ('SGS', 'GS'),
    'Saint Helena, Ascension and Tristan da Cunha': ('SHN', 'SH'),
    'Svalbard and Jan Mayen': ('SJM', 'SJ'),
    'Solomon Islands': ('SLB', 'SB'),
    'Sierra Leone': ('SLE', 'SL'),
    'El Salvador': ('SLV', 'SV'),
    'San Marino': ('SMR', 'SM'),
    'Somalia': ('SOM', 'SO'),
    'Saint Pierre and Miquelon': ('SPM', 'PM'),
    'Serbia': ('SRB', 'RS'),
    'South Sudan': ('SSD', 'SS'),
    'Sao Tome and Principe': ('STP', 'ST'),
    'Suriname': ('SUR', 'SR'),
    'Slovakia': ('SVK', 'SK'),
    'Slovenia': ('SVN', 'SI'),
    'Sweden': ('SWE', 'SE'),
    'Eswatini': ('SWZ', 'SZ'),
    'Sint Maarten (Dutch part)': ('SXM', 'SX'),
    'Seychelles': ('SYC', 'SC'),
    'Syrian Arab Republic': ('SYR', 'SY'),
    'Turks and Caicos Islands': ('TCA', 'TC'),
    'Chad': ('TCD', 'TD'),
    'Togo': ('TGO', 'TG'),
    'Thailand': ('THA', 'TH'),
    'Tajikistan': ('TJK', 'TJ'),
    'Tokelau': ('TKL', 'TK'),
    'Turkmenistan': ('TKM', 'TM'),
    'Timor-Leste': ('TLS', 'TL'),
    'Tonga': ('TON', 'TO'),
    'Trinidad and Tobago': ('TTO', 'TT'),
    'Tunisia': ('TUN', 'TN'),
    'Türkiye': ('TUR', 'TR'),
    'Tuvalu': ('TUV', 'TV'),
    'Taiwan, Province of China': ('TWN', 'TW'),
    'Tanzania, United Republic of': ('TZA', 'TZ'),
    'Uganda': ('UGA', 'UG'),
    'Ukraine': ('UKR', 'UA'),
    'Uruguay': ('URY', 'UY'),
    'United States of America': ('USA', 'US'),
    'United States Minor Outlying Islands': ('UMI', 'UM'),
    'Uzbekistan': ('UZB', 'UZ'),
    'Holy See': ('VAT', 'VA'),
    'Saint Vincent and the Grenadines': ('VCT', 'VC'),
    'Venezuela (Bolivarian Republic of)': ('VEN', 'VE'),
    'Virgin Islands (British)': ('VGB', 'VG'),
    'Virgin Islands (U.S.)': ('VIR', 'VI'),
    'Viet Nam': ('VNM', 'VN'),
    'Vanuatu': ('VUT', 'VU'),
    'Wallis and Futuna': ('WLF', 'WF'),
    'Samoa': ('WSM', 'WS'),
    'Yemen': ('YEM', 'YE'),
    'South Africa': ('ZAF', 'ZA'),
    'Zambia': ('ZMB', 'ZM'),
    'Zimbabwe': ('ZWE', 'ZW'),
}
