LANGUAGES_DICT = {
    'Abkhazian': ('abk', 'ab'),
    'Afar': ('aar', 'aa'),
    'Afrikaans': ('afr', 'af'),
    'Akan': ('aka', 'ak'),
    'Albanian': ('sqi', 'sq'),
    'Amharic': ('amh', 'am'),
    'Arabic': ('ara', 'ar'),
    'Aragonese': ('arg', 'an'),
    'Armenian': ('hye', 'hy'),
    'Assamese': ('asm', 'as'),
    'Avaric': ('ava', 'av'),
    'Avestan': ('ave', 'ae'),
    'Aymara': ('aym', 'ay'),
    'Azerbaijani': ('aze', 'az'),
    'Bambara': ('bam', 'bm'),
    'Bashkir': ('bak', 'ba'),
    'Basque': ('eus', 'eu'),
    'Belarusian': ('bel', 'be'),
    'Bengali': ('ben', 'bn'),
    'Bislama': ('bis', 'bi'),
    'Bosnian': ('bos', 'bs'),
    'Breton': ('bre', 'br'),
    'Bulgarian': ('bul', 'bg'),
    'Burmese': ('mya', 'my'),
    'Catalan, Valencian': ('cat', 'ca'),
    'Chamorro': ('cha', 'ch'),
    'Chechen': ('che', 'ce'),
    'Chichewa, Chewa, Nyanja': ('nya', 'ny'),
    'Chinese': ('zho', 'zh'),
    'Church Slavonic, Old Slavonic, Old Church Slavonic': ('chu', 'cu'),
    'Chuvash': ('chv', 'cv'),
    'Cornish': ('cor', 'kw'),
    'Corsican': ('cos', 'co'),
    'Cree': ('cre', 'cr'),
    'Croatian': ('hrv', 'hr'),
    'Czech': ('ces', 'cs'),
    'Danish': ('dan', 'da'),
    'Divehi, Dhivehi, Maldivian': ('div', 'dv'),
    'Dutch, Flemish': ('nld', 'nl'),
    'Dzongkha': ('dzo', 'dz'),
    'English': ('eng', 'en'),
    'Esperanto': ('epo', 'eo'),
    'Estonian': ('est', 'et'),
    'Ewe': ('ewe', 'ee'),
    'Faroese': ('fao', 'fo'),
    'Fijian': ('fij', 'fj'),
    'Finnish': ('fin', 'fi'),
    'French': ('fra', 'fr'),
    'Western Frisian': ('fry', 'fy'),
    'Fulah': ('ful', 'ff'),
    'Gaelic, Scottish Gaelic': ('gla', 'gd'),
    'Galician': ('glg', 'gl'),
    'Ganda': ('lug', 'lg'),
    'Georgian': ('kat', 'ka'),
    'German': ('deu', 'de'),
    'Greek, Modern (1453–)': ('ell', 'el'),
    'Kalaallisut, Greenlandic': ('kal', 'kl'),
    'Guarani': ('grn', 'gn'),
    'Gujarati': ('guj', 'gu'),
    'Haitian, Haitian Creole': ('hat', 'ht'),
    'Hausa': ('hau', 'ha'),
    'Hebrew': ('heb', 'he'),
    'Herero': ('her', 'hz'),
    'Hindi': ('hin', 'hi'),
    'Hiri Motu': ('hmo', 'ho'),
    'Hungarian': ('hun', 'hu'),
    'Icelandic': ('isl', 'is'),
    'Ido': ('ido', 'io'),
    'Igbo': ('ibo', 'ig'),
    'Indonesian': ('ind', 'id'),
    'Interlingua (International Auxiliary Language Association)': ('ina', 'ia'),
    'Interlingue, Occidental': ('ile', 'ie'),
    'Inuktitut': ('iku', 'iu'),
    'Inupiaq': ('ipk', 'ik'),
    'Irish': ('gle', 'ga'),
    'Italian': ('ita', 'it'),
    'Japanese': ('jpn', 'ja'),
    'Javanese': ('jav', 'jv'),
    'Kannada': ('kan', 'kn'),
    'Kanuri': ('kau', 'kr'),
    'Kashmiri': ('kas', 'ks'),
    'Kazakh': ('kaz', 'kk'),
    'Central Khmer': ('khm', 'km'),
    'Kikuyu, Gikuyu': ('kik', 'ki'),
    'Kinyarwanda': ('kin', 'rw'),
    'Kirghiz, Kyrgyz': ('kir', 'ky'),
    'Komi': ('kom', 'kv'),
    'Kongo': ('kon', 'kg'),
    'Korean': ('kor', 'ko'),
    'Kuanyama, Kwanyama': ('kua', 'kj'),
    'Kurdish': ('kur', 'ku'),
    'Lao': ('lao', 'lo'),
    'Latin': ('lat', 'la'),
    'Latvian': ('lav', 'lv'),
    'Limburgan, Limburger, Limburgish': ('lim', 'li'),
    'Lingala': ('lin', 'ln'),
    'Lithuanian': ('lit', 'lt'),
    'Luba-Katanga': ('lub', 'lu'),
    'Luxembourgish, Letzeburgesch': ('ltz', 'lb'),
    'Macedonian': ('mkd', 'mk'),
    'Malagasy': ('mlg', 'mg'),
    'Malay': ('msa', 'ms'),
    'Malayalam': ('mal', 'ml'),
    'Maltese': ('mlt', 'mt'),
    'Manx': ('glv', 'gv'),
    'Maori': ('mri', 'mi'),
    'Marathi': ('mar', 'mr'),
    'Marshallese': ('mah', 'mh'),
    'Mongolian': ('mon', 'mn'),
    'Nauru': ('nau', 'na'),
    'Navajo, Navaho': ('nav', 'nv'),
    'North Ndebele': ('nde', 'nd'),
    'South Ndebele': ('nbl', 'nr'),
    'Ndonga': ('ndo', 'ng'),
    'Nepali': ('nep', 'ne'),
    'Norwegian': ('nor', 'no'),
    'Norwegian Bokmål': ('nob', 'nb'),
    'Norwegian Nynorsk': ('nno', 'nn'),
    'Sichuan Yi, Nuosu': ('iii', 'ii'),
    'Occitan': ('oci', 'oc'),
    'Ojibwa': ('oji', 'oj'),
    'Oriya': ('ori', 'or'),
    'Oromo': ('orm', 'om'),
    'Ossetian, Ossetic': ('oss', 'os'),
    'Pali': ('pli', 'pi'),
    'Pashto, Pushto': ('pus', 'ps'),
    'Persian': ('fas', 'fa'),
    'Polish': ('pol', 'pl'),
    'Portuguese': ('por', 'pt'),
    'Punjabi, Panjabi': ('pan', 'pa'),
    'Quechua': ('que', 'qu'),
    'Romanian, Moldavian, Moldovan': ('ron', 'ro'),
    'Romansh': ('roh', 'rm'),
    'Rundi': ('run', 'rn'),
    'Russian': ('rus', 'ru'),
    'Northern Sami': ('sme', 'se'),
    'Samoan': ('smo', 'sm'),
    'Sango': ('sag', 'sg'),
    'Sanskrit': ('san', 'sa'),
    'Sardinian': ('srd', 'sc'),
    'Serbian': ('srp', 'sr'),
    'Shona': ('sna', 'sn'),
    'Sindhi': ('snd', 'sd'),
    'Sinhala, Sinhalese': ('sin', 'si'),
    'Slovak': ('slk', 'sk'),
    'Slovenian': ('slv', 'sl'),
    'Somali': ('som', 'so'),
    'Southern Sotho': ('sot', 'st'),
    'Spanish, Castilian': ('spa', 'es'),
    'Sundanese': ('sun', 'su'),
    'Swahili': ('swa', 'sw'),
    'Swati': ('ssw', 'ss'),
    'Swedish': ('swe', 'sv'),
    'Tagalog': ('tgl', 'tl'),
    'Tahitian': ('tah', 'ty'),
    'Tajik': ('tgk', 'tg'),
    'Tamil': ('tam', 'ta'),
    'Tatar': ('tat', 'tt'),
    'Telugu': ('tel', 'te'),
    'Thai': ('tha', 'th'),
    'Tibetan': ('bod', 'bo'),
    'Tigrinya': ('tir', 'ti'),
    'Tonga (Tonga Islands)': ('ton', 'to'),
    'Tsonga': ('tso', 'ts'),
    'Tswana': ('tsn', 'tn'),
    'Turkish': ('tur', 'tr'),
    'Turkmen': ('tuk', 'tk'),
    'Twi': ('twi', 'tw'),
    'Uighur, Uyghur': ('uig', 'ug'),
    'Ukrainian': ('ukr', 'uk'),
    'Urdu': ('urd', 'ur'),
    'Uzbek': ('uzb', 'uz'),
    'Venda': ('ven', 've'),
    'Vietnamese': ('vie', 'vi'),
    'Volapük': ('vol', 'vo'),
    'Walloon': ('wln', 'wa'),
    'Welsh': ('cym', 'cy'),
    'Wolof': ('wol', 'wo'),
    'Xhosa': ('xho', 'xh'),
    'Yiddish': ('yid', 'yi'),
    'Yoruba': ('yor', 'yo'),
    'Zhuang, Chuang': ('zha', 'za'),
    'Zulu': ('zul', 'zu'),
}
